### ISSUE TITLE
problems building per README

### ISSUE THREAD

**Issue by fredcy** [mblakele/goread#4]
The README refers to using the `goapp` program but I do not seem to have it. I installed the Google Cloud SDK on MacOS today, and also installed the app-engine-go components. What is the workaround?   `go get -d` runs cleanly.  But `go build` from the app directory gives me this:

```
$ go build
../../../mjibson/goread/main.go:35:2: cannot find package "appengine" in any of:
	/Users/fred/sdk/go1.11.9/src/appengine (from $GOROOT)
	/Users/fred/go/src/appengine (from $GOPATH)
 ...
```

(My apologies if this is a rookie kind of problem. I have not built for appengine in many years.)

**Comment by fredcy** [comment]
Hmm, app/app.go refers to "github.com/mjibson/goread"

**Comment by mblakele** [comment]
I think your source tree might contain a mix of old code from `mjibson/goread` and new code from https://github.com/mblakele/goread/pull/3

I'm saying that because this old code matches your error:

https://github.com/mjibson/goread/blob/master/main.go#L35

...but the code in my fork doesn't: the appengine package has been changed to `google.golang.org/appengine/(datastore|log)` and on lines 32-33 instead of 35:

https://github.com/mblakele/goread/blob/e357f624578676cc0547ce7680d11299edc9ce36/main.go#L32

If you want to use my fork, your git config should point to it. Mine looks like this:

```
$ git remote -v
mblakele	git@github.com:mblakele/goread.git (fetch)
mblakele	git@github.com:mblakele/goread.git (push)
origin	https://github.com/mjibson/goread (fetch)
origin	https://github.com/mjibson/goread (push)
```

Yours could look a little different, but it should have a remote that points to `mblakele/goread`

Then:

```
$ git stat 
On branch mblakele-dev-charset
Your branch is up to date with 'mblakele/mblakele-dev-charset'.
```

Does that help?

**Comment by mblakele** [comment]
> The README refers to using the `goapp` program but I do not seem to have it.

BTW I think `goapp` is obsolete. I haven't remove it from the readme because I wasn't 100% certain. This project is my only major contact with GCP, so I'm not as familiar with the tools as I'd like to be.

**Comment by mblakele** [comment]
> Hmm, app/app.go refers to "github.com/mjibson/goread"

That's fine — or anyway it matches my source tree.

**Comment by fredcy** [comment]
I had to change this line
https://github.com/mblakele/goread/blob/308e6e48c51414456318e96424b4e56593482237/app/app.go#L8
to refer to your repo and now it builds ok.

**Comment by mblakele** [comment]
> I had to change this line
> 
> https://github.com/mblakele/goread/blob/308e6e48c51414456318e96424b4e56593482237/app/app.go#L8
> 
> to refer to your repo and now it builds ok.

Glad to hear it. Maybe the difference is that my local build code still lives at `$GOPATH/src/github.com/mjibson/goread`, even though the remote is `mblakele/goread`? That would make sense — I never bothered to change it, but I suppose I should.

**Comment by fredcy** [comment]
That's probably what happened. I cloned your repo directly into src/github.com/mblakele/goread and built from there.

After changing that one line as above I can now build and deploy goread! Thank you so much for making this possible.

```
diff --git a/app/app.go b/app/app.go
index 21a74c8..135064d 100644
--- a/app/app.go
+++ b/app/app.go
@@ -5,7 +5,7 @@ import (

        "github.com/gorilla/mux"

-       app "github.com/mjibson/goread"
+       app "github.com/mblakele/goread"

        "google.golang.org/appengine"
 )
```
